language: python

python:
  - "3.6"

before_install:
  - git config --global user.name "$USERNAME" 
  - git config --global user.email "$EMAIL"

install:
  - pip install -r requirements.txt

script:
  - python fetch.py

after_script:
  - git add .
  - git commit -am "travis automated update helm charts"
  - git push --force -u --quiet "https://${GH_TOKEN}@${GH_REF}" master:charts
