language: python

sudo: required

python:
  - "3.7"

branches:
  only:
  - sync

before_install:
  - git config --global user.name "$USERNAME" 
  - git config --global user.email "$EMAIL"

install:
  - pip install -r requirements.txt

script:
  - chmod +x fetch.sh
  - ./fetch.sh
