
sudo: required

services:
  - docker

branches:
  only:
  - sync

before_install:
  - git config --global user.name "$USERNAME" 
  - git config --global user.email "$EMAIL"


script:
  - chmod +x fetch.sh
  - ./fetch.sh
