language: python

python:
  - "3.6"

branches:
  only:
  - sync

before_install:
  - git config --global user.name "$USERNAME" 
  - git config --global user.email "$EMAIL"

install:
  - pip install -r requirements.txt

script:
  - python fetch.py
  - git add .
  - git commit -am "travis automated update helm charts "
  - git checkout -B master
  - git merge sync
  - git push --force -u "https://$USERNAME:${GH_TOKEN}@${GH_REF}" master:master

notifications:
  email: false
